name: Deploy to Test Server
   
on:
  push:
    branches:
      - staging

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./src/     # Inhalt von src/ wird auf den Server kopiert
        server-dir: /www/vijabei/test/  # Hier deinen FTP-Pfad einsetzen
        dangerous-clean-slate: false
        exclude: |
        **/downloads/**
        **/feedback/**
        **/legacy/**
        **/logs/**
        **/*.log
        **/clickcounter-*.txt
        **/collection_logs.txt
        **/user_interactions.log
        google*.html
        **/*.zip