name: Deploy to Test Server

on:
  push:
    branches:
      - staging

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /www/vijabei/test/  # Insert your FTP path here
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/downloads/*.zip
          **/feedback/*
          !**/feedback/.htaccess
          **/logs/*
          !**/logs/.htaccess
          **/*.log
          google*.html
          README.md
          LICENSE.md
          *.sample.*
          **/*.sample.php
